export default {
  title: "LostPunks",
  url: "https://lostpunks.com",
  description: "Find CryptoPunks sitting in long-dormant wallets — by your own definition of 'lost.'",
  cryptopunksDetailsBase: "https://cryptopunks.app/cryptopunks/details/",
  cryptopunksAccountBase: "https://cryptopunks.app/cryptopunks/accountinfo?account=",
  evmNowAddressBase: "https://evm.now/address/",
  imageBase: "https://www.cryptopunks.app/api/punks/",
  burnedPunksUrl: "https://burnedpunks.com",
  museumPunksUrl: "https://museumpunks.com",
  openseaItemBase: "https://opensea.io/item/ethereum/",
  v1WrappedContract: "0x282BDD42f4eb70e7A9D9F40c8fEA0825B7f68C5D",
  v1UnwrappedContract: "0x6Ba6f2207e343923BA692e5Cae646Fb0F566DB8D",
  v2WrappedContract: "0xb7f7F6C52F2e2fdb1963Eab30438024864c313F6",
  punksMarketBase: "https://punksmarket.app/punk/",
  v1cryptopunksBase: "https://v1cryptopunks.com/details/",
};
